##############################
#	computes the average risk scores of a population
##############################

[public.statement]
value = 14

[private.data]
d1 = [ 1, 2, 1, 1, 2, 1, 0, 1,]
d2 = [ 2, 3,]

# dot products
# r[0] = (1,2)(2,3) = 2 + 6 = 8
# r[1] = (1,1)(2,3) = 2 + 3 = 5
# r[2] = (2,1)(2,3) = 4 + 3 = 7
# r[3] = (0,1)(2,3) = 0 + 3 = 3

# average
# ( 8 + 5 + 7 + 3 )/4 = 5.75 = 5